export { default as Dashboard } from './Dashboard'
export { default as Chat } from './Chat'
export { default as Tutors } from './Tutors'
export { default as Courses } from './Courses'
export { default as CourseView } from './CourseView'
export { default as Assignments } from './Assignments'
export { default as Leaderboard } from './Leaderboard'
export { default as Profile } from './Profile'
