import { useMemo, useRef, useState, type ChangeEvent } from 'react'
import { Edit, Mail, MapPin, Zap, BookOpen, Trophy, Calendar, X, Camera, Loader2, CheckCircle2 } from 'lucide-react'
import { jsPDF } from 'jspdf'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import { useApp } from '../state/AppContext'
import HeatMap from '../components/HeatMap'
import { API_BASE_URL, resolveMediaUrl } from '../config/api'

export default function Profile() {
    const { state, actions } = useApp()
    const navigate = useNavigate()
    const profile = state.profile

    const [isEditOpen, setIsEditOpen] = useState(false)
    const [fullName, setFullName] = useState(profile?.fullName ?? '')
    const [email, setEmail] = useState(profile?.email ?? state.user?.email ?? '')
    const [location, setLocation] = useState(profile?.location ?? '')
    const [bio, setBio] = useState(profile?.bio ?? '')
    const [isUploadingImage, setIsUploadingImage] = useState(false)
    const [uploadSuccess, setUploadSuccess] = useState('')
    const [uploadError, setUploadError] = useState('')
    const fileInputRef = useRef<HTMLInputElement>(null)

    const initials = useMemo(() => {
        const base = (profile?.fullName || state.user?.username || 'JD')
            .split(' ')
            .filter(Boolean)
            .slice(0, 2)
            .map((p) => p[0]?.toUpperCase())
            .join('')
        return base || 'JD'
    }, [profile?.fullName, state.user?.username])

    const completedCourses = useMemo(
        () => state.courses.filter((c) => c.enrollmentStatus === 'completed'),
        [state.courses],
    )
    const certificateCourse = completedCourses[0] ?? state.courses.find((c) => c.enrollmentStatus === 'enrolled') ?? state.courses[0]

    const issueDate = new Date().toLocaleDateString()
    const credentialId = useMemo(() => `EC-${Math.random().toString(16).slice(2, 10).toUpperCase()}`, [])
    const verificationLink = `https://educonnect.local/verify/${credentialId}`

    const stats = [
        { icon: BookOpen, label: 'Courses Completed', value: state.stats.coursesCompleted.toString(), color: 'from-blue-400 to-blue-600' },
        { icon: Zap, label: 'Current Streak', value: `${state.stats.learningStreak} days`, color: 'from-orange-400 to-orange-600' },
        { icon: Trophy, label: 'Achievements', value: '24', color: 'from-yellow-400 to-yellow-600' },
        { icon: Calendar, label: 'Learning Hours', value: '245 hrs', color: 'from-green-400 to-green-600' },
    ]

    const skills = [
        'React', 'JavaScript', 'TypeScript', 'Python', 'SQL', 'Web Design', 'DSA', 'Node.js',
    ]

    const downloadCertificate = () => {
        const doc = new jsPDF({ unit: 'pt', format: 'a4' })
        const w = doc.internal.pageSize.getWidth()
        const h = doc.internal.pageSize.getHeight()

        // Border
        doc.setDrawColor(99, 102, 241) // accent
        doc.setLineWidth(2)
        doc.rect(36, 36, w - 72, h - 72)

        // Header
        doc.setFillColor(99, 102, 241)
        doc.rect(36, 36, w - 72, 72, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(18)
        doc.text('EduConnect', 56, 78)

        doc.setTextColor(17, 24, 39)
        doc.setFontSize(28)
        doc.setFont('helvetica', 'bold')
        doc.text('CERTIFICATE OF COMPLETION', w / 2, 160, { align: 'center' })

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(14)
        doc.text('Presented to', w / 2, 210, { align: 'center' })

        doc.setFont('helvetica', 'bold')
        doc.setFontSize(22)
        doc.text(profile?.fullName || state.user?.username || 'Learner', w / 2, 250, { align: 'center' })

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(14)
        doc.text('For successfully completing certification requirements', w / 2, 295, { align: 'center' })

        doc.setFont('helvetica', 'bold')
        doc.setFontSize(16)
        doc.text(`Course: ${certificateCourse?.title ?? 'EduConnect Certification'}`, w / 2, 340, { align: 'center' })

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(12)
        doc.text(`Issued on: ${issueDate}`, 72, 420)
        doc.text(`Credential ID: ${credentialId}`, 72, 444)
        doc.text(`Verification: ${verificationLink}`, 72, 468)

        doc.setFontSize(10)
        doc.setTextColor(107, 114, 128)
        doc.text('This certificate is generated by EduConnect.', w / 2, h - 72, { align: 'center' })

        doc.save(`EduConnect-Certificate-${credentialId}.pdf`)
    }

    const handleProfileImageUpload = async (event: ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0]
        if (!file) return

        setUploadError('')
        setUploadSuccess('')
        const localPreview = URL.createObjectURL(file)
        actions.updateProfile({ profileImage: localPreview })

        const formData = new FormData()
        formData.append('file', file)

        setIsUploadingImage(true)
        try {
            const response = await axios.post(`${API_BASE_URL}/api/users/upload-profile-pic`, formData, {
                headers: { 'Content-Type': 'multipart/form-data' },
            })
            const savedUrl = response.data?.profileImageUrl
            if (savedUrl) {
                actions.updateProfile({ profileImage: savedUrl })
                setUploadSuccess('Profile image uploaded')
            } else {
                setUploadSuccess('Preview updated')
            }
        } catch (_error) {
            setUploadSuccess('Preview updated (offline)')
        } finally {
            setIsUploadingImage(false)
        }
    }

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-slate-950 animate-fade-in">
            {/* Cover Photo */}
            <div className="h-48 bg-gradient-to-r from-accent-500 to-accent-600" />

            <div className="max-w-4xl mx-auto px-6 pb-12">
                {/* Profile Header */}
                <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 -mt-24 relative z-10 p-6 mb-8">
                    <div className="flex items-start justify-between mb-6">
                        <div className="flex items-start gap-6 flex-1">
                            <div className="relative">
                                <div className="w-32 h-32 rounded-full bg-gradient-to-br from-accent-400 to-accent-600 text-white flex items-center justify-center font-bold text-4xl border-4 border-white dark:border-slate-800 shadow-lg overflow-hidden">
                                    {profile?.profileImage ? (
                                        <img src={resolveMediaUrl(profile.profileImage)} alt="Profile" className="w-full h-full object-cover" />
                                    ) : (
                                        initials
                                    )}
                                </div>
                                <input
                                    ref={fileInputRef}
                                    type="file"
                                    accept="image/*"
                                    className="hidden"
                                    onChange={handleProfileImageUpload}
                                />
                                <button
                                    type="button"
                                    onClick={() => fileInputRef.current?.click()}
                                    disabled={isUploadingImage}
                                    className="absolute -bottom-1 -right-1 w-10 h-10 rounded-full bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 shadow-md flex items-center justify-center hover:shadow-lg transition-all"
                                >
                                    {isUploadingImage ? <Loader2 size={16} className="animate-spin" /> : <Camera size={16} />}
                                </button>
                            </div>

                            <div className="flex-1 pt-4">
                                <div className="flex items-start gap-4 mb-4">
                                    <div>
                                        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">{profile?.fullName ?? state.user?.username}</h1>
                                        <div className="flex items-center gap-2 text-accent-600 dark:text-accent-400 font-semibold mt-1">
                                            <span className="text-2xl">⭐</span>
                                            <span>Role {state.user?.role} • {state.stats.communityPoints.toLocaleString()} Points</span>
                                        </div>
                                    </div>
                                </div>

                                <div className="space-y-2 text-gray-600 dark:text-gray-400">
                                    <div className="flex items-center gap-2">
                                        <Mail size={16} />
                                        <span>{profile?.email ?? state.user?.email}</span>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <MapPin size={16} />
                                        <span>{profile?.location ?? '—'}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button
                            onClick={() => {
                                setFullName(profile?.fullName ?? '')
                                setEmail(profile?.email ?? state.user?.email ?? '')
                                setLocation(profile?.location ?? '')
                                setBio(profile?.bio ?? '')
                                setIsEditOpen(true)
                            }}
                            className="p-3 bg-gradient-to-r from-accent-500 to-accent-600 text-white rounded-lg hover:shadow-lg transition-all duration-200 flex items-center gap-2"
                        >
                            <Edit size={18} />
                            Edit Profile
                        </button>
                    </div>

                    <p className="text-gray-600 dark:text-gray-400 text-lg">{profile?.bio ?? ''}</p>
                    {(uploadSuccess || uploadError) && (
                        <div className={`mt-3 inline-flex items-center gap-2 px-3 py-2 rounded-lg text-sm ${uploadError ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}>
                            {!uploadError && <CheckCircle2 size={14} />}
                            <span>{uploadError || uploadSuccess}</span>
                        </div>
                    )}
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
                        Joined {profile?.joinDateIso ? new Date(profile.joinDateIso).toLocaleDateString() : '—'}
                    </p>
                </div>

                {/* Stats Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                    {stats.map((stat) => (
                        <div key={stat.label} className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm border border-gray-200 dark:border-slate-700">
                            <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${stat.color} flex items-center justify-center text-white mb-4`}>
                                <stat.icon size={24} />
                            </div>
                            <p className="text-3xl font-bold text-gray-900 dark:text-white mb-1">{stat.value}</p>
                            <p className="text-sm text-gray-600 dark:text-gray-400">{stat.label}</p>
                        </div>
                    ))}
                </div>

                {/* Skills Section */}
                <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm border border-gray-200 dark:border-slate-700 mb-8">
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Skills</h2>
                    <div className="flex flex-wrap gap-2">
                        {skills.map((skill) => (
                            <span
                                key={skill}
                                className="px-4 py-2 bg-gradient-to-r from-accent-100 to-accent-200 dark:from-accent-900 dark:to-accent-800 text-accent-700 dark:text-accent-300 rounded-full font-semibold text-sm"
                            >
                                {skill}
                            </span>
                        ))}
                    </div>
                </div>

                {/* Completed Courses */}
                <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm border border-gray-200 dark:border-slate-700 mb-8">
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Completed Courses</h2>
                    <div className="space-y-4">
                        {(completedCourses.length > 0 ? completedCourses : []).map((course, idx) => (
                            <div key={idx} className="flex items-center justify-between p-4 bg-gray-50 dark:bg-slate-900 rounded-lg border border-gray-200 dark:border-slate-700">
                                <div>
                                    <h3 className="font-semibold text-gray-900 dark:text-white">{course.title}</h3>
                                    <p className="text-sm text-gray-600 dark:text-gray-400">By {course.instructor}</p>
                                </div>
                                <div className="text-right">
                                    <p className="font-semibold text-gray-900 dark:text-white">Completed</p>
                                    <p className="text-sm text-gray-600 dark:text-gray-400"> </p>
                                </div>
                            </div>
                        ))}
                        {completedCourses.length === 0 && (
                            <div className="p-4 bg-gray-50 dark:bg-slate-900 rounded-lg border border-gray-200 dark:border-slate-700 text-sm text-gray-600 dark:text-gray-400">
                                No completed courses yet.
                            </div>
                        )}
                    </div>
                </div>

                {/* Heat Map visualization (replaces Community Score + Tutor Sessions) */}
                <div className="mb-8">
                    <HeatMap seed={`${profile?.username ?? state.user?.username ?? 'educonnect'}-${state.stats.communityPoints}`} />
                </div>

                {/* Action Buttons */}
                <div className="flex gap-4">
                    <button
                        onClick={downloadCertificate}
                        className="flex-1 py-3 bg-gradient-to-r from-accent-500 to-accent-600 text-white rounded-lg hover:shadow-lg transition-all duration-200 font-semibold"
                    >
                        Download Certificate
                    </button>
                    <button className="flex-1 py-3 border-2 border-accent-600 text-accent-600 dark:text-accent-400 rounded-lg hover:bg-accent-50 dark:hover:bg-accent-900 transition-colors font-semibold">
                        Share Profile
                    </button>
                    <button
                        onClick={() => navigate('/settings')}
                        className="flex-1 py-3 border-2 border-gray-300 dark:border-slate-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-slate-900 transition-colors font-semibold"
                    >
                        Settings
                    </button>
                </div>
            </div>

            {/* Edit Profile Modal */}
            {isEditOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <button
                        type="button"
                        onClick={() => setIsEditOpen(false)}
                        className="absolute inset-0 bg-black/40"
                        aria-label="Close modal"
                    />
                    <div className="relative w-full max-w-xl bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-gray-200 dark:border-slate-800 overflow-hidden">
                        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-slate-800">
                            <h3 className="text-lg font-bold text-gray-900 dark:text-white">Edit Profile</h3>
                            <button
                                type="button"
                                onClick={() => setIsEditOpen(false)}
                                className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-800"
                            >
                                <X size={18} />
                            </button>
                        </div>
                        <div className="p-6 space-y-4">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Full Name</label>
                                    <input
                                        value={fullName}
                                        onChange={(e) => setFullName(e.target.value)}
                                        className="w-full px-4 py-2 bg-white dark:bg-slate-800 border border-gray-300 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-accent-500"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Email</label>
                                    <input
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                        className="w-full px-4 py-2 bg-white dark:bg-slate-800 border border-gray-300 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-accent-500"
                                    />
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Location</label>
                                <input
                                    value={location}
                                    onChange={(e) => setLocation(e.target.value)}
                                    className="w-full px-4 py-2 bg-white dark:bg-slate-800 border border-gray-300 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-accent-500"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Bio</label>
                                <textarea
                                    value={bio}
                                    onChange={(e) => setBio(e.target.value)}
                                    rows={4}
                                    className="w-full px-4 py-2 bg-white dark:bg-slate-800 border border-gray-300 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-accent-500"
                                />
                            </div>
                        </div>
                        <div className="px-6 py-4 border-t border-gray-200 dark:border-slate-800 flex items-center justify-end gap-3">
                            <button
                                onClick={() => setIsEditOpen(false)}
                                className="px-4 py-2 bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-gray-300 rounded-lg font-semibold hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={() => {
                                    actions.updateProfile({ fullName, email, location, bio })
                                    setIsEditOpen(false)
                                }}
                                className="px-4 py-2 bg-gradient-to-r from-accent-500 to-accent-600 text-white rounded-lg font-semibold hover:shadow-lg transition-all"
                            >
                                Save
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
