server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/educonnect_backend}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    # Use Render environment variables in production.
    secret: ${JWT_SECRET:bXktc3VwZXItc2VjdXJlLWp3dC1rZXktbXlzdC1iZS1hdC1sZWFzdC0zMi1ieXRlcw==}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
